
name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker rmi rmuks/bikeshare-fastapi:latest
    
      - name: Stop Old Docker Container
        run: sudo docker stop bikeshare-fastapi-container

      - name: Delete Old Docker Container  
        run: sudo docker rm bikeshare-fastapi-container
    
      
