name: Push a Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Pull Docker Image
      env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: sudo docker pull $DOCKER_USER/bikeshare-fastapi:latest

    - name: Delete Old Docker Container
      run: sudo docker rm -f bikeshare-fastapi-container || true

    - name: Run Docker Container
      env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: sudo docker run -it -d -p 8001:8001 --name bikeshare-fastapi-container $DOCKER_USER/bikeshare-fastapi:latest
